import Head from "next/head";
import styled from "styled-components";
import Homepage from "../components/Homepage";
import Sidebar from "../components/Sidebar";

const Container = styled.div`
  color: white;
  display: flex;
  background-color: #212e36;
`;

export default function Home() {
  return (
    <Container>
      <Head>
        <title>WhatsApp Web Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://www.freepnglogos.com/uploads/whatsapp-logo-app-png-4.png"
        />
      </Head>
      <Sidebar />
      <Homepage />
    </Container>
  );
}
